//
//  SourcePickerInteractor.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 27/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AVFoundation

protocol SourcePickerBusinessLogic {
    func doLoadSources(request: SourcePicker.LoadSources.Request)
    var videoAsset: AVAsset? { get set }
}

protocol SourcePickerDataStore {
    var videoAsset: AVAsset? { get set }
}

class SourcePickerInteractor: SourcePickerBusinessLogic, SourcePickerDataStore {
    var presenter: SourcePickerPresentationLogic?
    var worker: SourcePickerWorker?
    var videoAsset: AVAsset?
    
    func doLoadSources(request: SourcePicker.LoadSources.Request) {
        worker = SourcePickerWorker()
        let sources = worker!.createSources()
        
        let response = SourcePicker.LoadSources.Response(sources: sources)
        presenter?.presentSources(response: response)
    }
}
