//
//  SourcePickerRouter.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 27/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SourcePickerRoutingLogic {
    func routeToManagerViewController()
    func routeToConfiguration()
}

protocol SourcePickerDataPassing {
    var dataStore: SourcePickerDataStore? { get }
}

class SourcePickerRouter: NSObject, SourcePickerRoutingLogic, SourcePickerDataPassing {
    weak var viewController: SourcePickerViewController?
    var dataStore: SourcePickerDataStore?
    
    // MARK: Routing
    
    func routeToManagerViewController() {
        let managercontroller = OverlayManagerViewController()
        var destinationDS = managercontroller.router!.dataStore!
        passDataToOverlayManager(source: dataStore!, destination: &destinationDS)
        navigateToOverlayManager(source: viewController!, destination: managercontroller)
    }
    
    func routeToConfiguration() {
        let configurationVC = ConfigurationViewController()
        let nav = UINavigationController(rootViewController: configurationVC)
        self.viewController?.present(nav, animated: true, completion: nil)
    }

    // MARK: Navigation
    
    func navigateToOverlayManager(source: SourcePickerViewController, destination: OverlayManagerViewController) {
      source.show(destination, sender: nil)
    }
//
//    //MARK: Passing data
//
    func passDataToOverlayManager(source: SourcePickerDataStore, destination: inout OverlayManagerDataStore) {
        destination.videoAsset = source.videoAsset
    }
}
