//
//  SourcePickerWorker.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 27/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import DGPLibrary

class SourcePickerWorker {
    
    static let titles: [String] = ["Live Camera",
                                   "Library",
                                   "iCloud"]
    
    static let icons: [UIImage?] = [
        UIImage(symbol: .video),
        UIImage(symbol: .squareAndArrowUp),
        UIImage(symbol: .icloud)
    ]
    
    let types = SourceType.allCases
    
    func createSources() -> [Source] {
        var list: [Source] = []
        
        for i in (0..<types.count) {
            list.append( Source(type: types[i],
                                image: SourcePickerWorker.icons[i],
                                title: SourcePickerWorker.titles[i])
            )
        }
        
        return list
    }
}
