//
//  CameraRouter.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 28/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CameraRoutingLogic {
    
}

protocol CameraDataPassing {
    var dataStore: CameraDataStore? { get }
}

class CameraRouter: NSObject, CameraRoutingLogic, CameraDataPassing {
    weak var viewController: CameraViewController?
    var dataStore: CameraDataStore?
    
}
