//
//  ConfigurationRouter.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 2/4/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ConfigurationRoutingLogic {
    func routeToBack()
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ConfigurationDataPassing {
    var dataStore: ConfigurationDataStore? { get }
}

class ConfigurationRouter: NSObject, ConfigurationRoutingLogic, ConfigurationDataPassing {
    weak var viewController: ConfigurationViewController?
    var dataStore: ConfigurationDataStore?
    
    
    func routeToBack() {
        self.viewController?.dismiss(animated: true, completion: dataStore?.completionBlock)
    }
}
