//
//  ConfigurationPresenter.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 2/4/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfigurationPresentationLogic {
    func presentItems(response: ConfigurationScene.LoadItems.Response)
    func presentSaveItems(response: ConfigurationScene.SaveItems.Response)
}

class ConfigurationPresenter: ConfigurationPresentationLogic {
    weak var viewController: ConfigurationDisplayLogic?
    
    func presentItems(response: ConfigurationScene.LoadItems.Response) {
        let viewModel = ConfigurationScene.LoadItems.ViewModel(items: response.items)
        viewController?.displayItems(viewModel: viewModel)
    }
    
    func presentSaveItems(response: ConfigurationScene.SaveItems.Response) {
        viewController?.displaySaveItems(viewModel: ConfigurationScene.SaveItems.ViewModel())
    }
}
