//
//  ASLInterpreterModels.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 28/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ASLInterpreter {
    // MARK: Use cases
    
    enum DetectedWord {
        struct Request {
        }
        struct Response {
            var letter: String
        }
        struct ViewModel {
            var letter: String 
        }
    }
}

class Occurrence {
    var letter: String
    var times: Int
    
    init(letter: String, times: Int) {
        self.letter = letter
        self.times = times
    }
    
    func increment() {
        times += 1
    }
}
