//
//  ASLInterpreterPresenter.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 28/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ASLInterpreterPresentationLogic {
    func presentDetectedWord(response: ASLInterpreter.DetectedWord.Response)
}

class ASLInterpreterPresenter: ASLInterpreterPresentationLogic {
    weak var viewController: ASLInterpreterDisplayLogic?
    
    func presentDetectedWord(response: ASLInterpreter.DetectedWord.Response) {
        DispatchQueue.main.async { [weak self] in
            let viewModel = ASLInterpreter.DetectedWord.ViewModel(letter: response.letter)
            self?.viewController?.displayDetectedWord(viewModel: viewModel)
        }
    }
}
