//
//  OverlayManagerInteractor.swift
//  ASLInterpreter
//
//  Created by Daniel Gallego Peralta on 28/3/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import AVFoundation

protocol OverlayManagerBusinessLogic {
    var overlayViewController: UIViewController! { get set }
    var overlayParentView: UIView! { get set }
    var cameraViewController: CameraViewController! { get set }
    var videoAsset: AVAsset? { get set }
    var isPaused: Bool { get set }
}

protocol OverlayManagerDataStore {
    var overlayViewController: UIViewController! { get set }
    var overlayParentView: UIView! { get set }
    var cameraViewController: CameraViewController! { get set }
    var videoAsset: AVAsset? { get set }
    var isPaused: Bool { get set }
}

class OverlayManagerInteractor: OverlayManagerBusinessLogic, OverlayManagerDataStore {
    var presenter: OverlayManagerPresentationLogic?
    var worker: OverlayManagerWorker?
    var overlayViewController: UIViewController!
    var overlayParentView: UIView!
    var cameraViewController: CameraViewController!
    var videoAsset: AVAsset?
    
    var isPaused = false {
        didSet {
            if isPaused {
                cameraViewController?.pauseVideo()
            } else {
                cameraViewController?.resumeVideo()
            }
        }
    }
}
